# SpringBoot
server:
  port: 8090

info:
  app:
    name: '${spring.application.name}'

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'
    registerWithEureka: 'true'
    fetchRegistry: 'true'

# Api Gateway
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-patients
          uri: 'lb://microservice-patients'
          predicates:
            - Path=/patient/**
          filters:
            - PrefixPath=/api/v1
        - id: microservice-patienthistory
          uri: 'lb://microservice-patienthistory'
          predicates:
            - Path=/patHistory/**
          filters:
            - PrefixPath=/api/v1

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info