# SpringBoot
server:
  port: 8081

info:
  app:
    name: ${spring.application.name}

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'
    registerWithEureka: 'true'
    fetchRegistry: 'true'

# Api Gateway
spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      routes:
        - id: microservice-patients
          uri: lb://microservice-patients
          predicates:
            - Path=/patient/**

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info