server:
  port: 8081

spring:
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        ddl-auto: 'always'
    datasource:
      url: 'jdbc:mysql://localhost:3306/diabetecare'
      username: 'diabetecareusr'
      password: 'diabetecare123'
      initialize: 'true'

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'
    registerWithEureka: 'true'
    fetchRegistry: 'true'

#Personal configs
#Api version
api:
  ver: 'v1'

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info