server:
  port: 8082

spring:
  data:
    mongodb:
      host: 'localhost'
      port: '27017'
      database: 'diabetecare'
      #            username: ''
      #            password: ''
      auto-index-creation: 'true'


#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'
    registerWithEureka: 'true'
    fetchRegistry: 'true'

#Personal configs
#Api version
api:
  ver: 'v1'

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info